### PR TITLE
Add Fortnight

### PR DESCRIPTION
**Pull request by pleasegivesource**
It is an fork of quantum I work on for oldmc.org which is on 1.6.4 but used to be on 1.6.2 which means i still have a 1.6.2 version of it.

### CODE REVIEW

**Comment by RemainingToast** [comment]
fetch upstream

**Comment by BobIsMyManager** [comment]
upstream is where the fresh water is at man

**Comment by pleasegivesource** [comment]
says no updates to fetch so i dunno 🤷‍♂️

**Comment by BobIsMyManager** [comment]
yea lol

**Comment by pleasegivesource** [comment]
mkay i fetched upstream i was just being an idiot

**Pull request closed without merging**
