### PR TITLE
Add teahax idk

### PR DESCRIPTION
**Pull request by fuckyouthinkimboogieman**
private utility mod with cool muchachos =)

### CODE REVIEW

**Comment by CPacketPlayerAction** [comment]
btw basically everything was skidded is in credits :)

**Comment by CPacketPlayerAction** [comment]
if u dont wanna add becuz of "hax", u also can name it kernal.club

**Comment by pleasegivesource** [comment]
they probably don't want to add it because you didn't read contributing.md which states "Your submission is not a skid... skid: We define a skid as taking others code and passing it off as your own and not crediting the original work. A skid should not be confused with a port or a fork."

**Comment by CPacketPlayerAction** [comment]
I credited everything i skidded in the main channel of my discord, "info", channel with rules and some info bout project.
also i posted this pull request less then 24 hours so its ok that they arent replying. i just said that becuz they wont add forgehax due to hax in the name. so yea

**Comment by fuckyouthinkimboogieman** [comment]
nah

**Pull request closed without merging**
