### PR TITLE
ForgeHax

### PR DESCRIPTION
**Pull request by BobIsMyManager**
wtf hax!?!

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
hang on, i need to fix something

**Comment by BobIsMyManager** [comment]
there

**Comment by BobIsMyManager** [comment]
@RemainingToast the name is legit ForgeHax cant really just make it called forge lol

**Comment by ChiquitaV2** [comment]
I mean..... totally can... or forge utility mod 🤓

**Comment by BobIsMyManager** [comment]
Lmao

**Comment by BobIsMyManager** [comment]
Conflicts now bruh moment

**Comment by BobIsMyManager** [comment]
Fixed

**Comment by ChiquitaV2** [comment]
Ok so we should make a decision on this. I think actually calling it forge hack is out of the question considering bleach hack is just called bleach so I think it's either we called it Forge utility mod or we just don't put it in. It's up to you I'm fine either way.￼

**Comment by BobIsMyManager** [comment]
I mean, it's called forgehax, not forgehacks

**Comment by ChiquitaV2** [comment]
I mean it's implied. Does anyone else have a thought on this?

**Comment by BobIsMyManager** [comment]
You'd prob have to ping in the discord to get people to read this

**Comment by BobIsMyManager** [comment]
No one responded yet rip

**Comment by BobIsMyManager** [comment]
Pog I love conflicts

**Comment by BobIsMyManager** [comment]
Wait, I just realized FaxHax is in the repo, isn't that the same situation tho?

**Comment by ChiquitaV2** [comment]
Um... yes but owner exception 🤫

**Comment by BobIsMyManager** [comment]
ok

**Pull request closed without merging**
