### PR TITLE
Fixed spelling mistake, gamesense archived

### PR DESCRIPTION
**Pull request by BobIsMyManager**
Jnactive lol

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
also should prob change the fabric icon and the description since its no longer fabric only

**Comment by BobIsMyManager** [comment]
Very sad

**Comment by ChiquitaV2** [comment]
> also should prob change the fabric icon and the description since its no longer fabric only

We have plans too busy haven't gotten around to it also gs is dead? 😢

**Comment by BobIsMyManager** [comment]
> > also should prob change the fabric icon and the description since its no longer fabric only
> 
> We have plans too busy haven't gotten around to it also gs is dead? 😢

Yea prob gonna only work on the 1.16 version now

**Pull request merged**
