### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by IUDevman**
Updated for GS + Tensor.

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
I was already sad that has 1.12 was archived but 1.16 aswell?!?

**Comment by IUDevman** [comment]
> I was already sad that has 1.12 was archived but 1.16 aswell?!?

Yeah, The 1.16.5 version didn't really go anywhere. Any future public clients from me will probably be Tensor.

**Comment by BobIsMyManager** [comment]
Ok, can't wait!

**Comment by ChiquitaV2** [comment]
Hi IUDevman 🤗

**Pull request merged**
