### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OffeeX**

### CODE REVIEW

**Comment by fuckyouthinkimboogieman** [comment]
has a lot of skidded code. hud editor -> salhack, for example

**Comment by ChiquitaV2** [comment]
Hmmmmmmmmmmmm

**Comment by moomooooo** [comment]
Also not in correct alphabetical order. It should be after bleachhack lol

**Comment by DiOnFire** [comment]
hud editor from salhack? no comment.

**Comment by ChiquitaV2** [comment]
So um... ig I shouldn't merge...

**Comment by moomooooo** [comment]
🤪

**Comment by ChiquitaV2** [comment]
😽

**Comment by OffeeX** [comment]
@ChiquitaV2

**Comment by fuckyouthinkimboogieman** [comment]
Lemme add all the skidded code right here

**Comment by fuckyouthinkimboogieman** [comment]
old gui eas having this: https://github.com/pleasegivesource/SalHackSkid/blob/master/src/main/java/me/ionar/salhack/gui/click/effects/Snow.java (new one was written by me for 90% lmao)

https://github.com/TheFishDevs/Bloomware/blob/main/src/main/java/me/offeex/bloomware/api/util/ColorUtils.java - salhack

RenderUtils are pasted from cherry client

https://github.com/TheFishDevs/Bloomware/blob/main/src/main/java/me/offeex/bloomware/api/util/MovementUtil.java - postman/moneymod+2

https://github.com/TheFishDevs/Bloomware/blob/main/src/main/java/me/offeex/bloomware/api/util/RainbowUtil.java salhack

**Comment by ChiquitaV2** [comment]
So if you have skidded code add property credits to each class and/or to the README.md then I'll merge

**Comment by OffeeX** [comment]
> So if you have skidded code add property credits to each class and/or to the README.md then I'll merge

done.

**Pull request merged**
